#! /usr/bin/env python3

from contextlib import contextmanager
import os
import os.path

from forrest import run


PIDFILE = 'gump.pid'
RUN_MODE = os.environ['RUN_MODE'].lower()


@contextmanager
def lock():
  """ A context manager for locking a process to a single running instance.
  This context manager writes to a pidfile and if, in doing so, sees a previously
  existing one, will terminate the program.
  """
  if os.path.exists(PIDFILE):
    raise Exception('There\'s already a running instance.\nTerminating...')

  with open(PIDFILE, 'w') as f:
    f.write('.')

  try:
    yield None
  finally:
    os.remove(PIDFILE)


if __name__ == '__main__':
  with lock():
    run.main(mode=RUN_MODE)
