version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '[%(asctime)s] %(levelname)s %(name)s: %(message)s'

handlers:
  default:
    formatter: standard
    class: logging.StreamHandler

  file:
    formatter: standard
    class: logging.handlers.RotatingFileHandler
    filename: specio.log

loggers:
  '':
    handlers: [default, file]
    propagate: true
    level: DEBUG
