version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '[%(asctime)s] %(levelname)s %(name)s: %(message)s'

  json:
    format: '%(message)s'
    class: pythonjsonlogger.jsonlogger.JsonFormatter


handlers:
  default:
    formatter: standard
    class: logging.StreamHandler

  file:
    formatter: standard
    class: logging.handlers.RotatingFileHandler
    filename: specio.log

  json:
    class: logging.StreamHandler
    formatter: json


loggers:
  'forrest':
    handlers: [default, json]
    propagate: true
    level: DEBUG

root:
  handlers: [default]
  propagate: true
  level: DEBUG

