version: "3.7"

services:

  specio:
    build:
      context: ./specio
      target: development
    restart: always
    depends_on:
      - queue
    links:
      - queue
    entrypoint: /install/entrypoint
    volumes:
      - dropzone-users:/opt/dropzone/users
      - ./customers:/opt/customers
    environment:
      - RUN_MODE=head
    # Allow intercation with PDB
    stdin_open: true
    tty: true

  worker:
    build:
      context: ./specio
      target: development
    restart: always
    depends_on:
      - queue
      - selenium_hub
    links:
      - queue
      - selenium_hub:selenium_hub
    volumes:
      - dropzone-users:/opt/dropzone/users
      - ./customers:/opt/customers
    entrypoint: /install/entrypoint
    environment:
      - RUN_MODE=worker
      - BROWSER=remote
      - SELENIUM_URL=http://selenium_hub:4444/wd/hub
      - ENVIRONMENT=dev
      - PYTHONPATH=/app/veripy
    # Allow intercation with PDB
    stdin_open: true
    tty: true

  sftp:
    image: atmoz/sftp
    volumes:
        - dropzone-users:/home
        - ./sftp:/etc/sftp:ro
    ports:
        - "2222:22"

  queue:
    image: redis

  flower:
    image: mher/flower
    links:
      - queue
    ports:
        - "5555:5555"
    entrypoint: 'flower --broker=redis://queue:6379/0'

  #
  # Browser virtualization integration testing
  #
  selenium_hub:
    image: selenium/standalone-chrome-debug
    privileged: true
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "uploads:/uploads"

volumes:
  uploads:
  dropzone-users:
