version: "3.7"

services:

  specio:
    build:
      context: ./specio
      target: development
    restart: always
    depends_on:
      - pdfs
    volumes:
      - ./dropzone:/opt/dropzone
      - ./specio:/opt/specio
    entrypoint: /opt/specio/entrypoint
    # Allow intercation with PDB
    # environment:
    #   - WORKDIR=/opt/specio
    stdin_open: true
    tty: true

  pdfs:
    build:
      context: https://41125aab2214caa4fab5be0cb5dddb5fa96739a9:@github.com/Codebiosys/pdf-microservice.git
      dockerfile: Dockerfile-production
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./dropzone:/opt/dropzone
      - ./pdfs:/opt/config

  sftp:
    image: atmoz/sftp
    volumes:
        - ./dropzone:/home/test_user/upload
        - ./sftp:/etc/sftp:ro
    ports:
        - "2222:22"
