version: "3.7"

services:

  specio:
    build:
      context: ./specio
      target: development
    restart: on-failure
    depends_on:
      - queue
      - worker
      - selenium_hub
    links:
      - queue
      - selenium_hub
    volumes:
      - ./dropzone:/opt/dropzone
      - ./customers:/opt/customers
    environment:
      # Uncomment this line to enable file-watch mode.
      # - RUN_MODE=watch
      # These options allow the specio node to act as a worker when running
      # VeriPy directly from the CLI.
      - BROWSER=remote
      - SELENIUM_URL=http://selenium_hub:4444/wd/hub
      - ENVIRONMENT=dev
    # Allow intercation with PDB
    stdin_open: true
    tty: true

  worker:
    build:
      context: ./specio
      target: development
    restart: always
    depends_on:
      - queue
      - selenium_hub
    links:
      - queue
      - selenium_hub:selenium_hub
    volumes:
      - ./dropzone:/opt/dropzone
      - ./customers:/opt/customers
    environment:
      - RUN_MODE=worker
      - BROWSER=remote
      - SELENIUM_URL=http://selenium_hub:4444/wd/hub
      - ENVIRONMENT=dev
    # Allow intercation with PDB
    stdin_open: true
    tty: true

  queue:
    image: redis

  flower:
    image: mher/flower
    links:
      - queue
    ports:
        - "5555:5555"
    command: 'flower --broker=redis://queue:6379/0'

  #
  # Browser virtualization integration testing
  #
  selenium_hub:
    image: selenium/standalone-chrome-debug
    privileged: true
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "uploads:/uploads"

  #
  # Elk Logging Stack
  #

  elasticsearch:
    build: https://41125aab2214caa4fab5be0cb5dddb5fa96739a9:@github.com/Codebiosys/elk-stack.git#master:elasticsearch
    restart: always
    expose:
      - 9200
      - 9300
    environment:
      - LOGSPOUT=ignore
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  logstash:
    build: https://41125aab2214caa4fab5be0cb5dddb5fa96739a9:@github.com/Codebiosys/elk-stack.git#master:logstash
    depends_on:
      - elasticsearch
    restart: always
    expose:
      - 5000
      - 9600
    environment:
      - LOGSPOUT=ignore
      - DROP_NON_JSON=false
      - "xpack.security.enabled=false"
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

  logspout:
    build: https://41125aab2214caa4fab5be0cb5dddb5fa96739a9:@github.com/Codebiosys/elk-stack.git#master:logspout
    depends_on:
      - logstash
    restart: always
    environment:
      - ROUTE_URIS=logstash://logstash:5000
      - LOGSTASH_TAGS=docker-elk
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  kibana:
    build: https://41125aab2214caa4fab5be0cb5dddb5fa96739a9:@github.com/Codebiosys/elk-stack.git#master:kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"
    environment:
      - LOGSPOUT=ignore
      - "xpack.security.enabled=false"

volumes:
  uploads:
  elasticsearch:
